### ISSUE TITLE
PX COUNTERS - basic "counter" - new counter record in database w/ GraphQL

### ISSUE THREAD

**Issue by Falieson** [Falieson/planetx-boilerplate-rsksoa#12]
Instead of PostgresDB, start with sqlite (provided by react-starter-kit, and then switch it to postgres)

- [x] if there is no counter record in the database, create it
- [x] find latest counter and pass its value to the counter component rendering at the home ('/') route
- [x] clicking increment/decrement updates the counter record in the database
- [x] implement using Relay MODERN not the older relay package

**Comment by tijesunimi-peters** [comment]
@Falieson I have the updated version of this Issue strictly using the `react-relay` and I would like to push so you can review it

**Comment by Falieson** [comment]
@andela-tpeters I added rights for you to push, please make a new branch if you run into merge conflicts. In the future I'd suggest the typical opensource collaboration process of forking and make PRs

**Comment by tijesunimi-peters** [comment]
I have fixed the conflicts and everything seems to be working well on my end.

**Comment by Falieson** [comment]
Thank you very much for following up and fixing that @andela-tpeters !

**Comment by Falieson** [comment]
@andela-tpeters reading over your latest commit I still see `import Relay from 'react-relay/classic';`
